name: Build, test & lint

on:
    push:
        branches: [main]
    pull_request:
        branches: [main]
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest

        strategy:
            matrix:
                node-version: [24.x, 26.x]
                # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

        steps:
            - uses: actions/checkout@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: 'npm'
            - name: Cache Next.js build
              uses: actions/cache@v4
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-node${{ matrix.node-version }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-node${{ matrix.node-version }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - run: npm ci
            - run: npm run lint:output
            - name: Upload eslint results
              if: success() || failure()
              uses: github/codeql-action/upload-sarif@v2
              with:
                  sarif_file: output/eslint-result.sarif
            - run: npm run build --if-present
            - run: npm test
