name: Prepare new version

on:
  pull_request:
    types: [closed]
    branches: [main]
  workflow_dispatch:

jobs:
  testing:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm ci
      - run: npm run lint:output
      - name: Upload eslint results
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: output/eslint-result.sarif
      - run: npm run build --if-present
      - run: npm test

  tag:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: testing
    outputs:
      version: ${{ steps.bump-version.outputs.new_tag }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"

      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.67.0
        id: bump-version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RELEASE_BRANCHES: main
          REPO_OWNER: parts-picker
          WITH_V: true

  docker:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: tag
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: robguth/parts-picker:ui-${{ needs.tag.outputs.version }},robguth/parts-picker:ui-latest
