name: Prepare new version

on:
    push:
        branches: [main]
    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}
    cancel-in-progress: false

jobs:
    testing:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            actions: write
            security-events: write

        env:
            # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
            NODE_VERSION: 26.x

        steps:
            - uses: actions/checkout@v7
            - name: Use Node.js ${{ env.NODE_VERSION }}
              uses: actions/setup-node@v7
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  cache: 'npm'
            - name: Cache Next.js build
              uses: actions/cache@v6
              with:
                  path: ${{ github.workspace }}/.next/cache
                  key: ${{ runner.os }}-node${{ env.NODE_VERSION }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**/*.[jt]s', '**/*.[jt]sx') }}
                  restore-keys: |
                      ${{ runner.os }}-node${{ env.NODE_VERSION }}-nextjs-${{ hashFiles('**/package-lock.json') }}-
            - run: npm ci
            - run: npm run lint:output
            - name: Upload eslint results
              if: success() || failure()
              uses: github/codeql-action/upload-sarif@v4
              with:
                  sarif_file: output/eslint-result.sarif
            - run: npm run build --if-present
            - run: npm test

    tag:
        runs-on: ubuntu-latest
        needs: testing
        permissions:
            contents: write

        outputs:
            version: ${{ steps.bump-version.outputs.new_tag }}
        steps:
            - uses: actions/checkout@v7
              with:
                  fetch-depth: '0'

            - name: Bump version and push tag
              uses: anothrNick/github-tag-action@4ed44965e0db8dab2b466a16da04aec3cc312fd8 # 1.75.0
              id: bump-version
              env:
                  DEFAULT_BUMP: patch
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  RELEASE_BRANCHES: main
                  REPO_OWNER: parts-picker
                  WITH_V: true

    docker:
        runs-on: ubuntu-latest
        needs: tag
        permissions:
            contents: read
            actions: write
        steps:
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v4
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v4
            - name: Login to Docker Hub
              uses: docker/login-action@v4
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}
            - name: Build and push
              uses: docker/build-push-action@v7
              with:
                  push: true
                  tags: robguth/parts-picker:ui-${{ needs.tag.outputs.version }},robguth/parts-picker:ui-latest
                  cache-from: type=gha
                  cache-to: type=gha,mode=max

    deploy-on-dev:
      runs-on: ubuntu-latest
      needs: [ docker, tag ]
      permissions: {}
      steps:
        - name: Trigger dev deployment
          run: |
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.CHARTS_PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/parts-picker/parts-picker-charts/dispatches \
              -d '{"event_type":"run-dev-deployment","client_payload":{"frontend_version":"ui-${{ needs.tag.outputs.version }}"}}'
